36 order form validation check mobile format
GoToGroMSP-20/GoToGroMSP-20 pull request #9
Opened 2022-09-11 12:09 UTC by Baavi

Validation - check mobile format

2022-09-11 23:11 UTC, ShiroKatake commented on src/components/Utils/EmailFormat.js
> +    var result = true;
use `let` instead of `var` https://stackoverflow.com/questions/762011/what-is-the-difference-between-let-and-var

2022-09-11 23:11 UTC, ShiroKatake commented on src/components/Utils/EmailFormat.js
> +  var email_pattern = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
consider using `const` here. `var` is basically deprecated

2022-09-12 00:11 UTC, ShiroKatake commented on src/App.css
> +#orderform{
Do we still need this style?

2022-09-12 00:14 UTC, ShiroKatake commented on src/components/Utils/MobileFormat.js
> +  var mobile_pattern = /^[\d\s]{10,12}$/;
I can do `045 487945` and still pass, but that's an invalid mobile number. I think you should sanitize the string to be clear of spaces first before running the regex and just check for 10 digits

2022-09-12 07:12 UTC, RoryHowlettUni reviewed
A few other things to;
- Folder "Utils" should be made all lower-case. Can't remember the reason why but Khang informed me of this
- The input component is now expecting to receive either "validationStatus.success" instead of "true" and "validationStatus.failure" rather then false back from the validation functions. You'll have to include the new "validationStatus.js" utility function in both validation functions for this to work (I'm pretty sure anyway)
- Also don't forget to merge develop to this branch and resolve any merge conflicts before pushing to the online repo and doing a Pull Request :)

2022-09-22 01:46 UTC, ShiroKatake commented
There is a merge conflict in `App.js`, you need resolve that before you can merge

2022-09-23 04:59 UTC, Baavi commented
merge conflict resolved.

2022-09-23 05:07 UTC, Baavi commented on src/App.css
> +#orderform{
nope, removed it

2022-09-23 05:08 UTC, Baavi commented
Resolve all issues

2022-09-23 07:26 UTC, ShiroKatake requested changes
This looks good, there's just deleting the Button file and we should be good to go with this one

2022-09-23 07:26 UTC, ShiroKatake commented on src/components/Button/Button.jsx
> +};
We don't need to commit this file because we already have a `Button` component. You should delete it.

2022-09-23 08:45 UTC, ShiroKatake approved these changes
Looks good 🥇

2022-09-23 08:48 UTC, merged